export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const MOVE_TO_CART = 'MOVE_TO_CART';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const TOGGLE_SAVE_FOR_LATER = 'TOGGLE_SAVE_FOR_LATER';

